- 
  name: "Bowling Alone (2001)"
  urls: 
    - "http://www.amazon.com/Bowling-Alone-Collapse-American-Community/dp/0743203046/"
    - "http://product.half.ebay.com/Bowling-Alone-The-Collapse-and-Revival-of-American-Community-by-Robert-D-Putnam-2001-Paperback/1812266&tg=info"
